apiVersion: v1
kind: Secret
metadata:
  name: aurum-secrets
  namespace: aurum-matrimony
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme_prod_password"
  POSTGRES_USER: "aurum_user"
  REDIS_PASSWORD: "changeme_redis_password"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "changeme_minio_password"
  RABBITMQ_USER: "aurum_user"
  RABBITMQ_PASSWORD: "changeme_rabbitmq_password"
  SECRET_KEY: "changeme_jwt_secret_key_production"